### ISSUE TITLE
Cannot install (UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa2 in position 13: invalid start byte)

### ISSUE THREAD

**Issue by Pl0414141** [Cisco-Talos/DynDataResolver#8]
SO: Windows 10 V20H2 19042.685 (full updated)
Python: 3.8.7
Arch: X64
Processor: INTEL
IDA Pro: 7.5SP3

...
[DDR_INSTALLER][INFO] Network setup:
[DDR_INSTALLER][INFO] Please enter server PORT to listen on (Default is 5000) :
Traceback (most recent call last):
  File "C:\ddr_installer\DDR_INSTALLER.py", line 701, in <module>
    if install_deps(venv, ddr_default_dir):
  File "C:\ddr_installer\DDR_INSTALLER.py", line 418, in install_deps
    data = process.stdout.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa2 in position 13: invalid start byte

C:\ddr_installer>
...

Anyone can help?
Thanks

**Comment by jon1scr** [comment]
data = process.stdout.decode('Windows-1251')
